@extends('layouts.app')
@section('title', 'Quotation extraction')
@section('content')
@php($candidate = is_array($documentIntake->extraction_payload) ? $documentIntake->extraction_payload : [])
<div class="workflow-breadcrumb"><a href="{{ route('purchase-quotation-intakes.index') }}">Quotation intake</a><span>/</span><a href="{{ route('purchase-quotation-intakes.show', $intakeBatch) }}">Batch #{{ str_pad((string) $intakeBatch->id, 6, '0', STR_PAD_LEFT) }}</a><span>/</span><span>{{ $documentIntake->original_name }}</span></div>
<x-page-header :title="$documentIntake->original_name" description="Review the extracted quotation candidate against the private original."><x-slot:actions><a class="btn btn-outline-secondary" href="{{ route('purchase-quotation-intakes.documents.original', [$intakeBatch, $documentIntake]) }}">Open original</a>@if ($documentIntake->status === App\DocumentIntakeStatus::NeedsVerification)<a class="btn btn-primary" href="{{ route('purchase-quotation-intakes.documents.verification.create', [$intakeBatch, $documentIntake]) }}">Verify and create draft</a>@elseif (config('ai.enabled') && in_array($documentIntake->status, [App\DocumentIntakeStatus::Pending, App\DocumentIntakeStatus::Processing, App\DocumentIntakeStatus::Failed], true))<form method="POST" action="{{ route('purchase-quotation-intakes.documents.extract', [$intakeBatch, $documentIntake]) }}">@csrf<button class="btn btn-primary" type="submit">{{ $documentIntake->status === App\DocumentIntakeStatus::Failed ? 'Retry extraction' : 'Process quotation' }}</button></form>@endif</x-slot:actions></x-page-header>
@if ($documentIntake->status === App\DocumentIntakeStatus::Verified && $documentIntake->purchaseRequest)
    <div class="card"><div class="card-body p-4"><div class="d-flex flex-wrap align-items-start justify-content-between gap-3"><div><x-status-badge :status="$documentIntake->status" /><h2 class="h5 mt-3 mb-1">Purchase Request draft created</h2><p class="text-secondary mb-0">This quotation created {{ $documentIntake->purchaseRequest->request_no }} as a draft. It has not been submitted for approval.</p></div><a class="btn btn-primary" href="{{ route('purchase-requests.show', $documentIntake->purchaseRequest) }}">Open Purchase Request</a></div></div></div>
@elseif ($documentIntake->status === App\DocumentIntakeStatus::NeedsVerification && $candidate !== [])
    @if (! empty($documentIntake->extraction_warnings))<div class="alert alert-warning"><strong>Review these extraction checks</strong><ul class="mb-0 mt-2">@foreach ($documentIntake->extraction_warnings as $warning)<li>{{ $warning['message'] ?? 'Review this value against the original quotation.' }}</li>@endforeach</ul></div>@endif
    <div class="card mb-4"><div class="card-header"><h2 class="h6 mb-0">Quotation candidate</h2></div><div class="card-body p-4"><p class="small text-secondary">These values are untrusted, read-only candidate data. No Purchase Request has been created.</p><div class="row g-4">@foreach (['Vendor name' => $candidate['vendor_name'] ?? null, 'Quotation number' => $candidate['quotation_no'] ?? null, 'Quotation date' => $candidate['quotation_date'] ?? null, 'Valid until' => $candidate['valid_until'] ?? null, 'Currency' => $candidate['currency'] ?? null, 'Subtotal' => $candidate['subtotal'] ?? null, 'Tax' => $candidate['tax_amount'] ?? null, 'Total' => $candidate['total_amount'] ?? null] as $label => $value)<div class="col-sm-6 col-xl-3"><span class="detail-label">{{ $label }}</span><strong class="d-block text-break">{{ $value ?? 'Not found' }}</strong></div>@endforeach</div></div></div>
    <div class="card table-card"><div class="card-header"><h2 class="h6 mb-0">Extracted line items</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Description</th><th class="text-end">Quantity</th><th class="text-end">Unit price</th><th class="text-end">Subtotal</th></tr></thead><tbody>@forelse ($candidate['line_items'] ?? [] as $item)<tr><td>{{ $item['description'] ?? 'Not found' }}</td><td class="text-end">{{ $item['quantity'] ?? '—' }}</td><td class="text-end">{{ $item['unit_price'] ?? '—' }}</td><td class="text-end">{{ $item['subtotal'] ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">No line items were extracted.</td></tr>@endforelse</tbody></table></div></div>
@else
    <div class="card"><div class="card-body p-4"><div class="d-flex flex-wrap align-items-center gap-4 mb-4"><div><span class="detail-label">Status</span><x-status-badge :status="$documentIntake->status" /></div><div><span class="detail-label">Type</span><strong>{{ $documentIntake->typeLabel() }}</strong></div></div>@if ($documentIntake->status === App\DocumentIntakeStatus::Verified)<div class="alert alert-info mb-0">This quotation has already been verified. Its former draft is no longer available.</div>@elseif (! config('ai.enabled') && $documentIntake->status === App\DocumentIntakeStatus::Pending)<div class="alert alert-info mb-0">AI processing is disabled. This quotation remains safely pending.</div>@elseif ($documentIntake->status === App\DocumentIntakeStatus::Processing)<div class="alert alert-info mb-0">Extraction is processing.</div>@elseif ($documentIntake->status === App\DocumentIntakeStatus::Failed)<div class="alert alert-danger mb-0"><strong>Extraction failed.</strong><div class="mt-1">{{ $documentIntake->failure_reason ?? 'The quotation could not be extracted.' }}</div></div>@else<div class="alert alert-info mb-0">This quotation is waiting for extraction.</div>@endif</div></div>
@endif
@endsection
