<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Name</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $user?->name) }}" required maxlength="255"></div>
    <div class="col-md-6"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $user?->email) }}" required maxlength="255"></div>
    <div class="col-md-6"><label class="form-label" for="password">Password @if ($user)<span class="text-secondary fw-normal">(leave blank to keep current)</span>@endif</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" autocomplete="new-password" @required(! $user) minlength="8"></div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" @required(! $user) minlength="8"></div>
    <div class="col-md-4"><label class="form-label" for="role">Role</label><select class="form-select @error('role') is-invalid @enderror" id="role" name="role" required>@foreach ($roles as $role)<option value="{{ $role->value }}" @selected(old('role', $user?->role?->value ?? App\UserRole::Employee->value) === $role->value)>{{ ucfirst(strtolower($role->value)) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $user?->status?->value ?? App\UserStatus::Active->value) === $status->value)>{{ ucfirst(strtolower($status->value)) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label" for="department_id">Department</label><select class="form-select @error('department_id') is-invalid @enderror" id="department_id" name="department_id"><option value="">No department</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id', $user?->department_id) === (string) $department->id)>{{ $department->name }}{{ $department->status === App\MasterDataStatus::Active ? '' : ' (Inactive)' }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label" for="manager_id">Manager</label><select class="form-select @error('manager_id') is-invalid @enderror" id="manager_id" name="manager_id"><option value="">No manager</option>@foreach ($managers as $manager)<option value="{{ $manager->id }}" @selected((string) old('manager_id', $user?->manager_id) === (string) $manager->id)>{{ $manager->name }}{{ $manager->isActive() ? '' : ' (Inactive)' }}</option>@endforeach</select></div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Save user</button><a class="btn btn-outline-secondary" href="{{ route('users.index') }}">Cancel</a></div>
