@extends('layouts.app')
@section('title', 'Users')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h2 mb-1">Users</h1><p class="text-secondary mb-0">Maintain access, roles and organization assignments.</p></div><a class="btn btn-primary" href="{{ route('users.create') }}">Add user</a></div>
<form class="row g-2 mb-4" method="GET"><div class="col-md-5"><label class="visually-hidden" for="search">Search users</label><input class="form-control" id="search" name="search" value="{{ $search }}" placeholder="Search name, email or department"></div><div class="col-auto"><button class="btn btn-outline-secondary" type="submit">Search</button></div>@if ($search)<div class="col-auto"><a class="btn btn-link" href="{{ route('users.index') }}">Clear</a></div>@endif</form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>User</th><th>Role</th><th>Department</th><th>Manager</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>
@forelse ($users as $user)<tr><td><div class="fw-semibold">{{ $user->name }}</div><small class="text-secondary">{{ $user->email }}</small></td><td>{{ ucfirst(strtolower($user->role->value)) }}</td><td>{{ $user->department?->name ?? '—' }}@if ($user->department && $user->department->status === App\MasterDataStatus::Inactive) <span class="text-secondary">(Inactive)</span>@endif</td><td>{{ $user->manager?->name ?? '—' }}</td><td><span class="badge {{ $user->status === App\UserStatus::Active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst(strtolower($user->status->value)) }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('users.edit', $user) }}">Edit</a></td></tr>@empty<tr><td class="text-center text-secondary py-5" colspan="6">No users found.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $users->links() }}</div>
@endsection
