@extends('layouts.app')
@section('title', $expenseClaim->claim_no)
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><div class="text-secondary">{{ $expenseClaim->claim_no }}</div><h1 class="h2 mb-1">{{ $expenseClaim->title }}</h1><span class="badge text-bg-{{ $expenseClaim->status === App\ExpenseClaimStatus::Draft ? 'secondary' : 'primary' }}">{{ str($expenseClaim->status->value)->replace('_', ' ')->title() }}</span></div>
    <div class="d-flex gap-2">@can('update', $expenseClaim)<a class="btn btn-outline-primary" href="{{ route('expense-claims.edit', $expenseClaim) }}">Edit</a>@endcan @can('submit', $expenseClaim)<form method="POST" action="{{ route('expense-claims.submit', $expenseClaim) }}">@csrf<button class="btn btn-primary" type="submit">Submit for approval</button></form>@endcan</div>
</div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Claim details</h2><dl class="row mb-0"><dt class="col-sm-3">Employee</dt><dd class="col-sm-9">{{ $expenseClaim->employee->name }}</dd><dt class="col-sm-3">Department</dt><dd class="col-sm-9">{{ $expenseClaim->department->name }}</dd><dt class="col-sm-3">Description</dt><dd class="col-sm-9">{{ $expenseClaim->description }}</dd><dt class="col-sm-3">Claim total</dt><dd class="col-sm-9 fw-semibold">{{ App\Support\Money::of($expenseClaim->total_amount)->format($expenseClaim->currency) }}</dd></dl></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Expense items and receipts</h2><div class="vstack gap-3">@foreach ($expenseClaim->items as $item)
    <section class="border rounded p-3"><div class="row g-3"><div class="col-md-3"><small class="text-secondary d-block">Date</small>{{ $item->expense_date->format('j M Y') }}</div><div class="col-md-3"><small class="text-secondary d-block">Category</small>{{ $item->category->name }}</div><div class="col-md-3"><small class="text-secondary d-block">Merchant</small>{{ $item->merchant ?: 'Not specified' }}</div><div class="col-md-3"><small class="text-secondary d-block">Gross amount</small><strong>{{ App\Support\Money::of($item->amount)->format($expenseClaim->currency) }}</strong></div><div class="col-md-9"><small class="text-secondary d-block">Description</small>{{ $item->description }}</div><div class="col-md-3"><small class="text-secondary d-block">Tax included (informational)</small>{{ App\Support\Money::of($item->tax_amount)->format($expenseClaim->currency) }}</div></div>
        <div class="mt-3 pt-3 border-top"><h3 class="h6">Private receipt</h3>@forelse ($item->attachments as $attachment)<div class="d-flex justify-content-between gap-2 py-1"><a href="{{ route('attachments.download', $attachment) }}">{{ $attachment->original_name }}</a>@can('delete', $attachment)<form method="POST" action="{{ route('attachments.destroy', $attachment) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-link text-danger p-0" type="submit">Delete</button></form>@endcan</div>@empty@if ($item->receipt_required)<p class="text-danger small mb-2">A receipt is required before submission.</p>@else<p class="text-secondary small mb-2">This item is exempt from the receipt requirement.</p>@endif@endforelse
        @can('addAttachment', $item)<form class="row g-2 mt-1" method="POST" enctype="multipart/form-data" action="{{ route('expense-item-attachments.store', $item) }}">@csrf<div class="col-md-8"><label class="visually-hidden" for="attachment-{{ $item->id }}">Receipt</label><input class="form-control form-control-sm" id="attachment-{{ $item->id }}" name="attachment" type="file" required></div><div class="col-md-4"><button class="btn btn-sm btn-outline-primary" type="submit">Upload receipt</button></div></form>@endcan</div>
    </section>
@endforeach</div></div></div>
@if ($runtime = $expenseClaim->approvalInstances->first())<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Approval timeline</h2><p class="text-secondary">Workflow version {{ $runtime->workflowVersion->version }} · {{ $runtime->workflowRuleGroup->name }}</p><ol class="list-group list-group-numbered">@foreach ($runtime->steps as $step)<li class="list-group-item d-flex justify-content-between align-items-start"><div class="ms-2 me-auto"><div class="fw-semibold">{{ $step->name }}</div>@forelse ($step->assignments as $assignment)<small class="text-secondary">{{ $assignment->approver->name }} · {{ str($assignment->status->value)->title() }}</small>@empty<small class="text-secondary">Approver assigned when this step becomes active.</small>@endforelse</div><span class="badge text-bg-secondary">{{ str($step->status->value)->title() }}</span></li>@endforeach</ol></div></div>@endif
@can('delete', $expenseClaim)<div class="card border-danger"><div class="card-body"><h2 class="h5">Delete draft</h2><p class="text-secondary small">This removes the draft, its items, and receipts. The claim reference will not be reused.</p><form method="POST" action="{{ route('expense-claims.destroy', $expenseClaim) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Delete draft</button></form></div></div>@endcan
@endsection
