@extends('layouts.app')
@section('title', $workflowTemplate->name)
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('workflow-templates.index') }}">← Workflows</a><h1 class="h2 mt-2 mb-1">{{ $workflowTemplate->name }}</h1><p class="text-secondary mb-0">{{ $workflowTemplate->module_type->label() }} · {{ $workflowTemplate->code }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('workflow-templates.edit', $workflowTemplate) }}">Edit template</a><form method="POST" action="{{ route('workflow-versions.store', $workflowTemplate) }}">@csrf<button class="btn btn-primary" type="submit">New blank draft</button></form></div></div>
@if ($workflowTemplate->description)<p>{{ $workflowTemplate->description }}</p>@endif
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3"><h2 class="h5 mb-0">Versions</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Version</th><th>Status</th><th>Created by</th><th>Published</th><th class="text-end">Actions</th></tr></thead><tbody>
@foreach ($workflowTemplate->versions as $version)
<tr><td class="fw-semibold">Version {{ $version->version }}</td><td><span class="badge {{ $version->status === App\WorkflowVersionStatus::Published ? 'text-bg-success' : ($version->status === App\WorkflowVersionStatus::Draft ? 'text-bg-warning' : 'text-bg-secondary') }}">{{ ucfirst(strtolower($version->status->value)) }}</span></td><td>{{ $version->creator->name }}</td><td>{{ $version->published_at?->format('d M Y H:i') ?? '—' }}</td><td class="text-end"><div class="d-inline-flex flex-wrap gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('workflow-versions.edit', $version) }}">{{ $version->isDraft() ? 'Configure' : 'View' }}</a>@if ($version->status === App\WorkflowVersionStatus::Published)<form method="POST" action="{{ route('workflow-versions.clone', $version) }}">@csrf<button class="btn btn-sm btn-outline-secondary" type="submit">Clone to draft</button></form>@endif @if ($version->isDraft())<form method="POST" action="{{ route('workflow-versions.destroy', $version) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Delete draft</button></form>@endif</div></td></tr>
@endforeach
</tbody></table></div></div>
@endsection
