@extends('layouts.app')
@section('title', $purchaseRequest->request_no)
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><div class="text-secondary">{{ $purchaseRequest->request_no }}</div><h1 class="h2 mb-1">{{ $purchaseRequest->title }}</h1><span class="badge text-bg-{{ $purchaseRequest->status === App\PurchaseRequestStatus::Draft ? 'secondary' : 'primary' }}">{{ str($purchaseRequest->status->value)->replace('_', ' ')->title() }}</span></div>
    <div class="d-flex gap-2">@can('update', $purchaseRequest)<a class="btn btn-outline-primary" href="{{ route('purchase-requests.edit', $purchaseRequest) }}">Edit</a>@endcan @can('submit', $purchaseRequest)<form method="POST" action="{{ route('purchase-requests.submit', $purchaseRequest) }}">@csrf<button class="btn btn-primary" type="submit">Submit for approval</button></form>@endcan @can('withdraw', $purchaseRequest)<form method="POST" action="{{ route('purchase-requests.withdraw', $purchaseRequest) }}">@csrf<button class="btn btn-outline-danger" type="submit">Withdraw</button></form>@endcan</div>
</div>
@php($runtime = $purchaseRequest->approvalInstances->first())
@if ($purchaseRequest->status === App\PurchaseRequestStatus::ChangesRequested && $runtime)
    @php($changeRequest = $runtime->actions->where('action', App\ApprovalActionType::ChangesRequested)->last())
    <div class="alert alert-warning"><h2 class="h5">Changes requested</h2>@if ($changeRequest)<p class="mb-1">{{ $changeRequest->comment }}</p><div class="small text-secondary">Requested by {{ $changeRequest->actor?->name ?? 'an approver' }}@if ($changeRequest->step) at {{ $changeRequest->step->name }}@endif.</div>@endif @can('resubmit', $purchaseRequest)<form class="mt-3" method="POST" action="{{ route('purchase-requests.resubmit', $purchaseRequest) }}">@csrf<label class="form-label" for="resubmit-comment">Resubmission note <span class="text-secondary">(optional)</span></label><textarea class="form-control" id="resubmit-comment" name="comment" rows="2" maxlength="2000"></textarea><button class="btn btn-primary mt-2" type="submit">Resubmit for approval</button></form>@endcan</div>
@endif
<div class="row g-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Business details</h2><dl class="row mb-0"><dt class="col-sm-4">Requester</dt><dd class="col-sm-8">{{ $purchaseRequest->requester->name }}</dd><dt class="col-sm-4">Department</dt><dd class="col-sm-8">{{ $purchaseRequest->department->name }}</dd><dt class="col-sm-4">Category</dt><dd class="col-sm-8">{{ $purchaseRequest->category->name }}</dd><dt class="col-sm-4">Vendor</dt><dd class="col-sm-8">{{ $purchaseRequest->vendor?->name ?? 'Not selected' }}</dd><dt class="col-sm-4">Needed by</dt><dd class="col-sm-8">{{ $purchaseRequest->needed_by_date?->format('j M Y') ?? 'Not specified' }}</dd><dt class="col-sm-4">Justification</dt><dd class="col-sm-8">{{ $purchaseRequest->description }}</dd></dl></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Items</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Description</th><th class="text-end">Qty</th><th class="text-end">Unit price</th><th class="text-end">Subtotal</th></tr></thead><tbody>@foreach ($purchaseRequest->items as $item)<tr><td>{{ $item->description }}</td><td class="text-end">{{ $item->quantity }}</td><td class="text-end">{{ App\Support\Money::of($item->unit_price)->format($purchaseRequest->currency) }}</td><td class="text-end">{{ App\Support\Money::of($item->subtotal)->format($purchaseRequest->currency) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="3" class="text-end">Subtotal</th><td class="text-end">{{ App\Support\Money::of($purchaseRequest->subtotal)->format($purchaseRequest->currency) }}</td></tr><tr><th colspan="3" class="text-end">Tax</th><td class="text-end">{{ App\Support\Money::of($purchaseRequest->tax_amount)->format($purchaseRequest->currency) }}</td></tr><tr><th colspan="3" class="text-end">Total</th><th class="text-end">{{ App\Support\Money::of($purchaseRequest->total_amount)->format($purchaseRequest->currency) }}</th></tr></tfoot></table></div></div></div>
        @if ($runtime)<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Approval timeline</h2><p class="text-secondary">Workflow version {{ $runtime->workflowVersion->version }} · {{ $runtime->workflowRuleGroup->name }}</p><ol class="list-group list-group-numbered">@foreach ($runtime->steps as $step)<li class="list-group-item d-flex justify-content-between align-items-start"><div class="ms-2 me-auto"><div class="fw-semibold">{{ $step->name }}</div>@forelse ($step->assignments as $assignment)<small class="text-secondary">{{ $assignment->approver->name }} · {{ str($assignment->status->value)->title() }}</small>@empty<small class="text-secondary">Approver assigned when this step becomes active.</small>@endforelse</div><span class="badge text-bg-secondary">{{ str($step->status->value)->title() }}</span></li>@endforeach</ol><div class="mt-3">@foreach ($runtime->actions as $action)<div class="small text-secondary">{{ $action->created_at->format('j M Y H:i') }} · {{ str($action->action->value)->replace('_', ' ')->title() }}@if ($action->actor) by {{ $action->actor->name }}@endif</div>@endforeach</div></div></div>@endif
    </div>
    <div class="col-lg-4">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Attachments</h2>@forelse ($purchaseRequest->attachments as $attachment)<div class="d-flex justify-content-between gap-2 py-2 border-bottom"><a href="{{ route('attachments.download', $attachment) }}">{{ $attachment->original_name }}</a>@can('delete', $attachment)<form method="POST" action="{{ route('attachments.destroy', $attachment) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-link text-danger p-0" type="submit">Delete</button></form>@endcan</div>@empty<p class="text-secondary">No attachments.</p>@endforelse @can('addAttachment', $purchaseRequest)<form class="mt-3" method="POST" enctype="multipart/form-data" action="{{ route('purchase-request-attachments.store', $purchaseRequest) }}">@csrf<label class="form-label" for="attachment">Add private attachment</label><input class="form-control" id="attachment" name="attachment" type="file" required><button class="btn btn-outline-primary mt-2" type="submit">Upload</button></form>@endcan</div></div>
        @can('delete', $purchaseRequest)<div class="card border-danger"><div class="card-body"><h2 class="h5">Delete draft</h2><p class="text-secondary small">This removes the draft, its items, and attachments. The request number will not be reused.</p><form method="POST" action="{{ route('purchase-requests.destroy', $purchaseRequest) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Delete draft</button></form></div></div>@endcan
    </div>
</div>
@endsection
