@extends('layouts.app')
@section('title', $supplierInvoice->internal_no)
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><div class="text-secondary">{{ $supplierInvoice->internal_no }}</div><h1 class="h2 mb-1">{{ $supplierInvoice->invoice_no }}</h1><span class="badge text-bg-{{ $supplierInvoice->status === App\SupplierInvoiceStatus::Draft ? 'secondary' : 'primary' }}">{{ str($supplierInvoice->status->value)->replace('_', ' ')->title() }}</span></div>
    <div class="d-flex gap-2">@can('update', $supplierInvoice)<a class="btn btn-outline-primary" href="{{ route('supplier-invoices.edit', $supplierInvoice) }}">Edit</a>@endcan @can('submit', $supplierInvoice)<form method="POST" action="{{ route('supplier-invoices.submit', $supplierInvoice) }}">@csrf<button class="btn btn-primary" type="submit">Submit for approval</button></form>@endcan</div>
</div>
<div class="row g-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Invoice details</h2><dl class="row mb-0"><dt class="col-sm-4">Vendor</dt><dd class="col-sm-8">{{ $supplierInvoice->vendor->name }}</dd><dt class="col-sm-4">Department</dt><dd class="col-sm-8">{{ $supplierInvoice->department->name }}</dd><dt class="col-sm-4">Category</dt><dd class="col-sm-8">{{ $supplierInvoice->category->name }}</dd><dt class="col-sm-4">Entered by</dt><dd class="col-sm-8">{{ $supplierInvoice->submittedBy->name }}</dd><dt class="col-sm-4">Invoice date</dt><dd class="col-sm-8">{{ $supplierInvoice->invoice_date->format('j M Y') }}</dd><dt class="col-sm-4">Due date</dt><dd class="col-sm-8">{{ $supplierInvoice->due_date?->format('j M Y') ?? 'Not specified' }}</dd><dt class="col-sm-4">Description</dt><dd class="col-sm-8">{{ $supplierInvoice->description }}</dd></dl></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Line items</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Description</th><th class="text-end">Quantity</th><th class="text-end">Unit price</th><th class="text-end">Subtotal</th></tr></thead><tbody>@foreach ($supplierInvoice->items as $item)<tr><td>{{ $item->description }}</td><td class="text-end">{{ rtrim(rtrim($item->quantity, '0'), '.') }}</td><td class="text-end">{{ App\Support\Money::of($item->unit_price)->format($supplierInvoice->currency) }}</td><td class="text-end">{{ App\Support\Money::of($item->subtotal)->format($supplierInvoice->currency) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="3" class="text-end">Subtotal</th><td class="text-end">{{ App\Support\Money::of($supplierInvoice->subtotal)->format($supplierInvoice->currency) }}</td></tr><tr><th colspan="3" class="text-end">Tax</th><td class="text-end">{{ App\Support\Money::of($supplierInvoice->tax_amount)->format($supplierInvoice->currency) }}</td></tr><tr><th colspan="3" class="text-end">Total</th><th class="text-end">{{ App\Support\Money::of($supplierInvoice->total_amount)->format($supplierInvoice->currency) }}</th></tr></tfoot></table></div></div></div>
        @if ($runtime = $supplierInvoice->approvalInstances->first())<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Approval timeline</h2><p class="text-secondary">Workflow version {{ $runtime->workflowVersion->version }} · {{ $runtime->workflowRuleGroup->name }}</p><ol class="list-group list-group-numbered">@foreach ($runtime->steps as $step)<li class="list-group-item d-flex justify-content-between align-items-start"><div class="ms-2 me-auto"><div class="fw-semibold">{{ $step->name }}</div>@forelse ($step->assignments as $assignment)<small class="text-secondary">{{ $assignment->approver->name }} · {{ str($assignment->status->value)->title() }}</small>@empty<small class="text-secondary">Approver assigned when this step becomes active.</small>@endforelse</div><span class="badge text-bg-secondary">{{ str($step->status->value)->title() }}</span></li>@endforeach</ol><div class="mt-3">@foreach ($runtime->actions as $action)<div class="small text-secondary">{{ $action->created_at->format('j M Y H:i') }} · {{ str($action->action->value)->replace('_', ' ')->title() }}@if ($action->actor) by {{ $action->actor->name }}@endif</div>@endforeach</div></div></div>@endif
    </div>
    <div class="col-lg-4">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Private attachments</h2>@forelse ($supplierInvoice->attachments as $attachment)<div class="d-flex justify-content-between gap-2 py-2 border-bottom"><a href="{{ route('attachments.download', $attachment) }}">{{ $attachment->original_name }}</a>@can('delete', $attachment)<form method="POST" action="{{ route('attachments.destroy', $attachment) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-link text-danger p-0" type="submit">Delete</button></form>@endcan</div>@empty<p class="text-secondary">Attach the supplier invoice document before submission.</p>@endforelse @can('addAttachment', $supplierInvoice)<form class="mt-3" method="POST" enctype="multipart/form-data" action="{{ route('supplier-invoice-attachments.store', $supplierInvoice) }}">@csrf<label class="form-label" for="attachment">Add invoice document</label><input class="form-control" id="attachment" name="attachment" type="file" required><button class="btn btn-outline-primary mt-2" type="submit">Upload</button></form>@endcan</div></div>
        @can('delete', $supplierInvoice)<div class="card border-danger"><div class="card-body"><h2 class="h5">Delete draft</h2><p class="text-secondary small">This removes the draft, its items, and attachments. The internal number will not be reused.</p><form method="POST" action="{{ route('supplier-invoices.destroy', $supplierInvoice) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Delete draft</button></form></div></div>@endcan
    </div>
</div>
@endsection
